# basic options
plugins:
  - jekyll-feed
title: Android Developer Blog
author: Dmitry Samoylenko
email: site@dmitrysamoylenko.in
description: This is a personal blog. Mail me if you want to use materials from it.
twitter_username: DmitrySamoylenk
github_username:  samoylenkodmitry
linkedin: dmitrysamoylenko
defaults:
  # _posts
  - scope:
      path: ""
      type: posts
    values:
      comments: true

disqus: 
  shortname: http-dmitrysamoylenko-com
# Build settings
markdown: kramdown
theme: minima
